baseURL = 'https://iacopy.github.io/hugosite'
languageCode = 'en-us'
title = 'Just a sandbox'
theme = "ananke"

[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "About"
weight = 0
identifier = "about" # this button will refer to a markdown file named "about" in the content folder
pre = "<br />"
url = "/about"
